version: '3'
services:
  frontend:
    container_name: next
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/code
      - /code/node_modules
    ports:
      - '3030:3030'